"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import {
  Sparkles,
  Send,
  ChevronDown,
  User,
  Building,
  Target,
  Wand2,
  Loader2,
} from "lucide-react";
import { getInvestors, getProfile, saveEmail, seedDemoData } from "../lib/actions";
import { Investor, CompanyProfile, EmailConfig } from "../lib/types";
import { buildColdEmailPrompt } from "../lib/prompt";

function ComposeContent() {
  const searchParams = useSearchParams();
  const preselectedId = searchParams.get("investorId");

  const [investors, setInvestors] = useState<Investor[]>([]);
  const [profile, setProfile] = useState<CompanyProfile | null>(null);
  const [selectedInvestorId, setSelectedInvestorId] = useState<string>("");
  const [generating, setGenerating] = useState(false);
  const [generatedVariants, setGeneratedVariants] = useState<
    Array<{ variant: number; subject: string; body: string; hookStyle: string; whyThisWorks: string; risk: string }>
  >([]);
  const [apiKey, setApiKey] = useState("");
  const [showConfig, setShowConfig] = useState(false);

  const [config, setConfig] = useState<EmailConfig>({
    tone: "conversational",
    length: "medium",
    hookStyle: "Specific praise of their thesis",
    structure: "Hook-Why-Ask",
    ctaStyle: "Direct (15-min slot)",
    followUpCount: 2,
    variants: 2,
  });

  useEffect(() => {
    seedDemoData().then(async () => {
      const [invs, prof] = await Promise.all([getInvestors(), getProfile()]);
      setInvestors(invs);
      setProfile(prof);
    });
    if (preselectedId) setSelectedInvestorId(preselectedId);
    // Load saved API key
    const savedKey = typeof window !== "undefined" ? localStorage.getItem("outreach_api_key") : null;
    if (savedKey) setApiKey(savedKey);
  }, [preselectedId]);

  const selectedInvestor = investors.find((i) => i.id === selectedInvestorId);

  const handleGenerate = async () => {
    if (!selectedInvestor || !profile) return;

    setGenerating(true);
    setGeneratedVariants([]);
    
    const dpdpEnabled = typeof window !== "undefined" ? localStorage.getItem("dpdp_enabled") !== "false" : true;
    const dpdpFooter = dpdpEnabled ? `\n\n---\n*This email was sent in accordance with the Digital Personal Data Protection Act, 2023. If you no longer wish to receive updates from us, please reply "unsubscribe".*` : "";

    // If API key provided, use real AI. Otherwise, generate demo variants.
    if (apiKey) {
      try {
        localStorage.setItem("outreach_api_key", apiKey);
        const prompt = buildColdEmailPrompt(
          profile,
          selectedInvestor.name,
          selectedInvestor.firm,
          selectedInvestor.notes,
          config
        );

        const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: "llama-3.3-70b-versatile",
            messages: [{ role: "user", content: prompt }],
            temperature: 0.8,
            max_tokens: 2000,
          }),
        });

        const data = await response.json();
        const content = data.choices?.[0]?.message?.content;
        if (content) {
          let parsedVariants: any[] = [];
          try {
            const parsed = JSON.parse(content);
            parsedVariants = Array.isArray(parsed) ? parsed : [parsed];
          } catch {
            const match = content.match(/\[[\s\S]*\]/);
            if (match) {
              parsedVariants = JSON.parse(match[0]);
            } else {
              parsedVariants = [
                {
                  variant: 1,
                  subject: "AI-generated email",
                  body: content,
                  hookStyle: config.hookStyle,
                  whyThisWorks: "Generated by AI",
                  risk: "Review carefully before sending",
                },
              ];
            }
          }
          
          if (dpdpFooter) {
            parsedVariants = parsedVariants.map(v => ({ ...v, body: v.body + dpdpFooter }));
          }
          setGeneratedVariants(parsedVariants);
        }
      } catch (err) {
        console.error("AI generation failed:", err);
        generateDemoVariants();
      }
    } else {
      generateDemoVariants();
    }

    setGenerating(false);
  };

  const generateDemoVariants = () => {
    if (!selectedInvestor || !profile) return;
    const variants = [];
    for (let i = 1; i <= config.variants; i++) {
      variants.push({
        variant: i,
        subject:
          i === 1
            ? `${profile.sector} — ${profile.revenue} MRR, growing ${profile.growthRate}`
            : `${profile.companyName}: solving ${profile.problem.split(" ").slice(0, 5).join(" ")}...`,
        body:
          i === 1
            ? `Hi ${selectedInvestor.name},\n\n${selectedInvestor.notes ? `I noticed your focus on ${selectedInvestor.tags[0] || "startups"} — ` : ""}${profile.problem}.\n\nWe're building ${profile.companyName}: ${profile.oneLiner}. ${profile.product}.\n\nTraction so far:\n• Revenue: ${profile.revenue}\n• Users: ${profile.users}\n• Growth: ${profile.growthRate}\n${profile.loisWaitlist ? `• Pipeline: ${profile.loisWaitlist}` : ""}\n\nWe're raising ${profile.amountRaising} (${profile.roundStructure}), with ${profile.alreadyCommitted} already committed.\n\nWould you have 15 minutes this week to hear our approach?\n\nBest,\n${profile.founderName}\n${profile.founderRole}, ${profile.companyName}`
            : `Hi ${selectedInvestor.name},\n\n${profile.differentiator}. That's what makes ${profile.companyName} different.\n\n${profile.insight}.\n\nIn ${profile.users}, we've proven the model works — ${profile.revenue} in revenue, growing ${profile.growthRate}.\n\n${profile.comparableExits ? `Comparable exits in our space: ${profile.comparableExits}.` : ""}\n\nWe're raising ${profile.amountRaising}. Happy to share our deck if this is within your thesis.\n\nBest,\n${profile.founderName}\n${profile.founderRole}, ${profile.companyName}`,
        hookStyle: i === 1 ? "Sharp metric" : "Insight-first",
        whyThisWorks:
          i === 1
            ? "Opens with a specific reference to the investor's focus, then leads with traction numbers. The metric-heavy approach works well for data-driven investors."
            : "Leads with the differentiator/insight instead of numbers. Works better for thesis-driven investors who want to understand the 'why' before the 'what'.",
        risk:
          i === 1
            ? "If the investor isn't numbers-focused, the dense traction section might feel like a pitch deck dump."
            : "The softer opening might not grab attention from investors who get 50+ emails/day.",
      });
    }
    
    const dpdpEnabled = typeof window !== "undefined" ? localStorage.getItem("dpdp_enabled") !== "false" : true;
    if (dpdpEnabled) {
      const footer = `\n\n---\n*This email was sent in accordance with the Digital Personal Data Protection Act, 2023. If you no longer wish to receive updates from us, please reply "unsubscribe".*`;
      variants.forEach(v => v.body += footer);
    }
    
    setGeneratedVariants(variants);
  };

  const handleSaveAsDraft = async (variant: (typeof generatedVariants)[0]) => {
    if (!selectedInvestor) return;
    await saveEmail({
      investorId: selectedInvestor.id,
      subject: variant.subject,
      body: variant.body,
      status: "draft",
      scheduledAt: null,
      sentAt: null,
      approved: false,
      variant: variant.variant,
      hookStyle: variant.hookStyle,
      whyThisWorks: variant.whyThisWorks,
      risk: variant.risk,
    });
    alert("Saved to drafts! Go to AI Drafts to review and approve.");
  };

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl md:text-3xl font-bold" style={{ color: "var(--foreground)" }}>
          Compose Email
        </h1>
        <p className="text-sm mt-1" style={{ color: "var(--muted)" }}>
          Select an investor and let AI draft personalized outreach
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Config Panel */}
        <div className="lg:col-span-1 space-y-5">
          {/* Select Investor */}
          <div className="glass-card p-5">
            <div className="flex items-center gap-2 mb-4">
              <User size={16} style={{ color: "var(--accent)" }} />
              <h3 className="text-sm font-bold" style={{ color: "var(--foreground)" }}>
                Select Investor
              </h3>
            </div>
            <select
              className="input"
              value={selectedInvestorId}
              onChange={(e) => setSelectedInvestorId(e.target.value)}
            >
              <option value="">Choose an investor...</option>
              {investors.map((inv) => (
                <option key={inv.id} value={inv.id}>
                  {inv.name} — {inv.firm}
                </option>
              ))}
            </select>
            {selectedInvestor && (
              <div className="mt-3 p-3 rounded-xl" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
                <p className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                  {selectedInvestor.name}
                </p>
                <p className="text-xs" style={{ color: "var(--muted)" }}>
                  {selectedInvestor.firm} • {selectedInvestor.email}
                </p>
                {selectedInvestor.notes && (
                  <p className="text-xs mt-2" style={{ color: "var(--muted)" }}>
                    {selectedInvestor.notes}
                  </p>
                )}
              </div>
            )}
          </div>

          {/* API Key */}
          <div className="glass-card p-5">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles size={16} style={{ color: "var(--accent)" }} />
              <h3 className="text-sm font-bold" style={{ color: "var(--foreground)" }}>
                AI Configuration
              </h3>
            </div>
            <label className="label">Groq API Key (optional)</label>
            <input
              className="input text-sm"
              type="password"
              placeholder="gsk_... (leave empty for demo mode)"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
            />
            <p className="text-xs mt-2 font-medium" style={{ color: "var(--muted)" }}>
              {apiKey ? "✓ Using Groq Llama 3.3 70B" : "Demo mode — generates template emails"}
            </p>
          </div>

          {/* Email Config */}
          <div className="glass-card p-5">
            <button
              className="flex items-center justify-between w-full mb-1"
              onClick={() => setShowConfig(!showConfig)}
            >
              <div className="flex items-center gap-2">
                <Target size={16} style={{ color: "var(--accent)" }} />
                <h3 className="text-sm font-bold" style={{ color: "var(--foreground)" }}>
                  Email Config
                </h3>
              </div>
              <ChevronDown
                size={16}
                className="transition-transform"
                style={{
                  color: "var(--muted)",
                  transform: showConfig ? "rotate(180deg)" : "rotate(0deg)",
                }}
              />
            </button>
            {showConfig && (
              <div className="mt-5 space-y-4">
                <div>
                  <label className="label mb-2">Tone</label>
                  <select
                    className="input"
                    value={config.tone}
                    onChange={(e) => setConfig({ ...config, tone: e.target.value as EmailConfig["tone"] })}
                  >
                    <option value="formal">Formal Indian English</option>
                    <option value="conversational">Conversational</option>
                    <option value="bold">Bold Founder Voice</option>
                    <option value="technical">Technical</option>
                  </select>
                </div>
                <div>
                  <label className="label mb-2">Length</label>
                  <select
                    className="input"
                    value={config.length}
                    onChange={(e) => setConfig({ ...config, length: e.target.value as EmailConfig["length"] })}
                  >
                    <option value="short">Short (≤120 words)</option>
                    <option value="medium">Medium (150-200)</option>
                    <option value="long">Long (220-280)</option>
                  </select>
                </div>
                <div>
                  <label className="label mb-2">Hook Style</label>
                  <select
                    className="input"
                    value={config.hookStyle}
                    onChange={(e) => setConfig({ ...config, hookStyle: e.target.value })}
                  >
                    <option>Specific praise of their thesis</option>
                    <option>Customer pain story</option>
                    <option>Sharp metric</option>
                    <option>Mutual contact name-drop</option>
                    <option>Personal connection</option>
                  </select>
                </div>
                <div>
                  <label className="label mb-2">Variants</label>
                  <select
                    className="input"
                    value={config.variants}
                    onChange={(e) => setConfig({ ...config, variants: parseInt(e.target.value) })}
                  >
                    <option value="1">1 variant</option>
                    <option value="2">2 variants</option>
                    <option value="3">3 variants</option>
                  </select>
                </div>
              </div>
            )}
          </div>

          {/* Generate Button */}
          <button
            className="btn-primary w-full justify-center text-base py-3"
            onClick={handleGenerate}
            disabled={!selectedInvestor || !profile || generating}
            style={{ opacity: !selectedInvestor || !profile ? 0.5 : 1 }}
          >
            {generating ? (
              <>
                <Loader2 size={18} className="animate-spin" /> Generating...
              </>
            ) : (
              <>
                <Wand2 size={18} /> Generate Email
              </>
            )}
          </button>

          {!profile && (
            <p className="text-xs text-center" style={{ color: "#f59e0b" }}>
              ⚠ Set up your company profile in Settings first
            </p>
          )}
        </div>

        {/* Right: Generated Variants */}
        <div className="lg:col-span-2 space-y-5">
          {generatedVariants.length === 0 && !generating ? (
            <div className="glass-card p-12 flex flex-col items-center justify-center text-center">
              <div
                className="w-16 h-16 rounded-2xl flex items-center justify-center mb-4"
                style={{ background: "rgba(99, 102, 241, 0.1)" }}
              >
                <Wand2 size={28} style={{ color: "var(--accent)", opacity: 0.5 }} />
              </div>
              <h3 className="text-lg font-bold mb-2" style={{ color: "var(--foreground)" }}>
                Ready to compose
              </h3>
              <p className="text-sm max-w-sm" style={{ color: "var(--muted)" }}>
                Select an investor and click "Generate Email" to create personalized outreach variants using AI.
              </p>
            </div>
          ) : generating ? (
            <div className="glass-card p-12 flex flex-col items-center justify-center">
              <div className="w-12 h-12 border-2 border-t-transparent rounded-full animate-spin mb-4" style={{ borderColor: "var(--accent)", borderTopColor: "transparent" }} />
              <p className="text-sm font-medium" style={{ color: "var(--foreground)" }}>
                AI is drafting your emails...
              </p>
            </div>
          ) : (
            generatedVariants.map((variant) => (
              <div key={variant.variant} className="glass-card p-5 animate-slide-up">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <span
                      className="text-[11px] px-2 py-1 rounded-full font-semibold"
                      style={{ background: "rgba(139, 92, 246, 0.15)", color: "#a78bfa" }}
                    >
                      Variant {variant.variant}
                    </span>
                    <span className="text-xs" style={{ color: "var(--muted)" }}>
                      {variant.hookStyle}
                    </span>
                  </div>
                </div>

                <p className="text-sm font-bold mb-3" style={{ color: "var(--foreground)" }}>
                  Subject: {variant.subject}
                </p>

                <div
                  className="text-sm whitespace-pre-wrap leading-relaxed mb-4 p-4 rounded-xl"
                  style={{
                    background: "var(--surface)",
                    border: "1px solid var(--border)",
                    color: "var(--foreground)",
                  }}
                >
                  {variant.body}
                </div>

                {variant.whyThisWorks && (
                  <div
                    className="text-xs p-3 rounded-lg mb-3"
                    style={{ background: "rgba(16, 185, 129, 0.08)", border: "1px solid rgba(16, 185, 129, 0.2)" }}
                  >
                    <span className="font-semibold" style={{ color: "#10b981" }}>✦ Why this works:</span>{" "}
                    <span style={{ color: "var(--muted)" }}>{variant.whyThisWorks}</span>
                  </div>
                )}
                {variant.risk && (
                  <div
                    className="text-xs p-3 rounded-lg mb-4"
                    style={{ background: "rgba(245, 158, 11, 0.08)", border: "1px solid rgba(245, 158, 11, 0.2)" }}
                  >
                    <span className="font-semibold" style={{ color: "#f59e0b" }}>⚠ Risk:</span>{" "}
                    <span style={{ color: "var(--muted)" }}>{variant.risk}</span>
                  </div>
                )}

                <button
                  className="btn-primary btn-sm"
                  onClick={() => handleSaveAsDraft(variant)}
                >
                  <Send size={14} /> Save to Drafts
                </button>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

export default function ComposePage() {
  return (
    <Suspense fallback={
      <div className="flex items-center justify-center h-[60vh]">
        <div className="w-8 h-8 border-2 border-t-transparent rounded-full animate-spin" style={{ borderColor: "var(--accent)", borderTopColor: "transparent" }} />
      </div>
    }>
      <ComposeContent />
    </Suspense>
  );
}
